### ISSUE TITLE
Add FastDigialPin as type

### ISSUE THREAD

**Issue by hreintke** [jfpoilpret/fast-arduino-lib#74]
I do not (yet) have a github fork from your repository so this as an issue.

I am not experienced in c++ templates but looking thru your code and a lot of reading :
When you add : 
```
	template<board::DigitalPin DPIN_>
	using FastDigitalPin = typename FastPinType<DPIN_>::TYPE;
	/// @endcond

}
#endif /* FASTIO_HH */
/// @endcond 

```
to the end of `gpio.h` 
You add the functionality to use 
```
     FastDigitalPin<DigitalPin::LED> led{PinMode::FASTOUTPUT};
```
as alternative for 
```
     FastPinType<DigitalPin::LED>::TYPE led2(PinMode::FASTOUTPUT);
```
Leading to more readable an understandable code

**Comment by jfpoilpret** [comment]
Hi @hreintke this looks interesting indeed, thank you for this suggestion.
I'll need to check out that this can work in all situations before adding it.
For that, I think the best is to use it in all FastArduino examples and check everything builds OK.

**Comment by jfpoilpret** [comment]
I'll work on it for next version 1.5.
I'll also need to:
- add API doc
- update tutorial to include this new API

**Comment by jfpoilpret** [comment]
Issue implemented on master branch as per commit https://github.com/jfpoilpret/fast-arduino-lib/commit/f3485e01fdd1179f17fdc16cc8c18c5bd216f148
